version: 2

project_name: snake

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: snake
    homepage: https://github.com/samf/snake
    description: CLI for The Snake Can temporary file storage
    repository:
      owner: samf
      name: homebrew-samf
      token: "{{ .Env.GH_PAT }}"
    directory: "."
    test: |
      system "#{bin}/snake", "--help"
